@ECHO OFF
IF  EXIST  "%VS120COMNTOOLS%"  CALL  "%VS120COMNTOOLS%vsvars32.bat"
IF  EXIST  "%VS110COMNTOOLS%"  CALL  "%VS110COMNTOOLS%vsvars32.bat"
IF  EXIST  "%VS100COMNTOOLS%"  CALL  "%VS100COMNTOOLS%vsvars32.bat"

CD %1
IF NOT EXIST "build"          MKDIR build
CD build
CMAKE -G "NMake Makefiles" ..
NMAKE
cd ..
cd ..